# This is a basic workflow to help you get started with Actions

name: ONE-YAML

# Controls when the workflow will run
on:
  push:
    branches:
      - main
      - test

jobs:
  Project-Setup:
    runs-on: ubuntu-latest
    steps:
      - name: first-execution
        if: ${{ secrets.FLAG == 'false' }}
        run: | 
          echo "Project Setup success" 

  Post-Setup:
    runs-on: ubuntu-latest
    steps:  
      - name:  nth-execution
        run: |
          ${{ job.Project-Setup.status }}
          echo "Project already setup moving to CodeQL Runner ID - ${{ github.run_number }}"