# This is a basic workflow to help you get started with Actions

name: ONE-YAML

# Controls when the workflow will run
on:
  push:
    branches:
      - main

jobs:
  build:
    if: ${{ github.run_number == '1' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a line script
        run: |
          echo "This is ONE-YAML"
          echo ${{github.run_number}}