# This is a basic workflow to help you get started with Actions

name: ONE-YAML

# Controls when the workflow will run
on:
  push:
    branches:
      - main
      - test

env:
  FLAG: ${{ secrets.FLAG }} 

jobs:
  Project-Setup:
    runs-on: ubuntu-latest
    steps:
      - name: first-execution
        if: ${{ env.FLAG == 'false' }}
        run: | 
          echo "Project Setup success" 

  Post-Setup:
    runs-on: ubuntu-latest
    steps:
      - name: nth-execution
        if: ${{ success() }}
        run: |
          gh secret set FLAG --body true
          echo "Project already setup moving to CodeQL Runner ID - ${{ github.run_number }}"
          echo ${{ env.FLAG }}
        env:
        GITHUB_TOKEN: ${{ secrets.GHTOKEN }}