# This is a basic workflow to help you get started with Actions

name: ONE-YAML

# Controls when the workflow will run
on:
  push:
    branches:
      - main

jobs:
  build:
    steps:
      runs-on: ubuntu-latest
      first-execution:
        if: ${{ github.run_number == '1' }}
        steps:
          - run: echo "Project Setup success"

      nth-execution:
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        steps:
          - run: echo "Project already setup moving to CodeQL"