# This is a basic workflow to help you get started with Actions

name: ONE-YAML

# Controls when the workflow will run
on:
  push:
    branches:
      - main
      - test

jobs:
  Project-Setup:
    runs-on: ubuntu-latest
    steps:
      - name: first-execution
        if: ${{ github.run_number == '1' }}
        run: echo "Project Setup success"

      - name:  nth-execution
        run: echo "Project already setup moving to CodeQL Runner ID - ${{ github.run_number }}"