# This is a basic workflow to help you get started with Actions

name: ONE-YAML

# Controls when the workflow will run
on:
  push:
    branches:
      - main
      - test

env:
  FLAG: ${{ secrets.FLAG }} 

jobs:
  Project-Setup:
    if: ${{ env.FLAG == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - name: first-execution
        run: | 
          echo "Project Setup success." 
        
      # - name: Update flag
      #   run: gh secret set FLAG --body "true"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GHTOKEN }}  

  Post-Setup:
    runs-on: ubuntu-latest
    steps:
      - name: nth-execution
        if: ${{ success() }}
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'FLAG'
          value: 'true'
          repository: Rahul-0312/test2
          token: ${{ secrets.GHTOKEN }}
