# This is a basic workflow to help you get started with Actions

name: ONE-YAML

# Controls when the workflow will run
on:
  push:
    branches:
      - main

jobs:
  build:
  runs-on: ubuntu-latest

  steps:
   first-execution:
     runs-on: ubuntu-latest
     if: ${{ github.run_number == '1' }}
     steps:
       - run: echo "Project Setup success"

   nth-execution:
     runs-on: ubuntu-latest
     if: ${{ github.event.workflow_run.conclusion == 'failure' }}
     steps:
       - run: echo "Project already setup moving to CodeQL"