on:
  workflow_run:
    workflows: [ONE-YAML]
    types:
      - completed

jobs:
   CodeQL:
     runs-on: ubuntu-latest
     steps:
      - name: first-execution
        run: echo "CodeQL execution."